// =============================================================================
// HYDRA-UMC Ecosystem - proto/hydra_common.proto
// Copyright (C) 2026 JuanenRac (Electro Hobby 3D) <electrohobby3d@gmail.com>
// GPL-3.0 - see LICENSE
//
// Shared gRPC contract for node-to-node traffic across the ecosystem's AI
// and orchestration nodes (Vision AI Node, Cognitive AI Node, Orchestration
// & Swarm, Digital Twin & Simulation families).
//
// This does NOT replace:
//   - REST + WebSocket between STUDIO/HYDRA-UMC-ANDROID-CONTROL/
//     HYDRA-UMC-IOS-CONTROL and HYDRA-UMC-SERVER (human-facing client
//     traffic, out of scope here).
//   - CAN / CAN-OTA on the real HYDRA-UMC/URTC firmware (STM32 boards do
//     not, and will not, speak gRPC).
//   - The physical E-STOP signal path: HYDRA-UMC-SAFETY-ZONES may request
//     a stop over this channel, but the firmware is what actually asserts
//     it over CAN, independent of this protocol's own health.
//
// Design rationale, alternatives considered, and per-family service sketch:
// see SONNET/13.DISENO_GRPC_NODOS_IA.txt (private planning doc, not part of
// this public repo).
//
// Status: v0. HealthService (below) is meant to be implemented by every
// node without exception - it is what lets HYDRA-UMC-NODE-HEALING probe
// any node in the ecosystem the same way. Per-family business services
// (vision detections, cognitive intents, job dispatch, physics stepping,
// ...) are intentionally NOT defined here yet - they get their own .proto
// file once each node's real logic lands, once there's an actual
// implementation to design the exact message shape against.
// =============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: hydra_common.proto

package hydracommonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployTarget int32

const (
	DeployTarget_DEPLOY_TARGET_UNSPECIFIED DeployTarget = 0
	DeployTarget_DEPLOY_TARGET_CM5         DeployTarget = 1
	DeployTarget_DEPLOY_TARGET_USER_PC     DeployTarget = 2
	DeployTarget_DEPLOY_TARGET_MOBILE      DeployTarget = 3
	DeployTarget_DEPLOY_TARGET_WEARABLE    DeployTarget = 4
)

// Enum value maps for DeployTarget.
var (
	DeployTarget_name = map[int32]string{
		0: "DEPLOY_TARGET_UNSPECIFIED",
		1: "DEPLOY_TARGET_CM5",
		2: "DEPLOY_TARGET_USER_PC",
		3: "DEPLOY_TARGET_MOBILE",
		4: "DEPLOY_TARGET_WEARABLE",
	}
	DeployTarget_value = map[string]int32{
		"DEPLOY_TARGET_UNSPECIFIED": 0,
		"DEPLOY_TARGET_CM5":         1,
		"DEPLOY_TARGET_USER_PC":     2,
		"DEPLOY_TARGET_MOBILE":      3,
		"DEPLOY_TARGET_WEARABLE":    4,
	}
)

func (x DeployTarget) Enum() *DeployTarget {
	p := new(DeployTarget)
	*p = x
	return p
}

func (x DeployTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeployTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_hydra_common_proto_enumTypes[0].Descriptor()
}

func (DeployTarget) Type() protoreflect.EnumType {
	return &file_hydra_common_proto_enumTypes[0]
}

func (x DeployTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeployTarget.Descriptor instead.
func (DeployTarget) EnumDescriptor() ([]byte, []int) {
	return file_hydra_common_proto_rawDescGZIP(), []int{0}
}

type HealthState int32

const (
	HealthState_HEALTH_STATE_UNSPECIFIED HealthState = 0
	HealthState_HEALTH_STATE_OK          HealthState = 1
	HealthState_HEALTH_STATE_DEGRADED    HealthState = 2 // running, but flagging a real concern
	// (e.g. a queue backing up)
	HealthState_HEALTH_STATE_UNHEALTHY HealthState = 3 // cannot currently fulfil its role
)

// Enum value maps for HealthState.
var (
	HealthState_name = map[int32]string{
		0: "HEALTH_STATE_UNSPECIFIED",
		1: "HEALTH_STATE_OK",
		2: "HEALTH_STATE_DEGRADED",
		3: "HEALTH_STATE_UNHEALTHY",
	}
	HealthState_value = map[string]int32{
		"HEALTH_STATE_UNSPECIFIED": 0,
		"HEALTH_STATE_OK":          1,
		"HEALTH_STATE_DEGRADED":    2,
		"HEALTH_STATE_UNHEALTHY":   3,
	}
)

func (x HealthState) Enum() *HealthState {
	p := new(HealthState)
	*p = x
	return p
}

func (x HealthState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthState) Descriptor() protoreflect.EnumDescriptor {
	return file_hydra_common_proto_enumTypes[1].Descriptor()
}

func (HealthState) Type() protoreflect.EnumType {
	return &file_hydra_common_proto_enumTypes[1]
}

func (x HealthState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthState.Descriptor instead.
func (HealthState) EnumDescriptor() ([]byte, []int) {
	return file_hydra_common_proto_rawDescGZIP(), []int{1}
}

// Mirrors what every node's skeleton entry point already prints today
// (name, version, one-line role) - just structured instead of a stdout
// string.
type NodeIdentity struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // e.g. "HYDRA-UMC-VISION-NODE"
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // odometer-scheme version, e.g. "0.1.4"
	Role    string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`       // one-line role description, already exists today
	Family  string                 `protobuf:"bytes,4,opt,name=family,proto3" json:"family,omitempty"`   // e.g. "vision-ai-node", "cognitive-ai-node",
	// "orchestration-swarm", "digital-twin-simulation"
	Deploy        DeployTarget `protobuf:"varint,5,opt,name=deploy,proto3,enum=hydra.common.v1.DeployTarget" json:"deploy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeIdentity) Reset() {
	*x = NodeIdentity{}
	mi := &file_hydra_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdentity) ProtoMessage() {}

func (x *NodeIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_hydra_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdentity.ProtoReflect.Descriptor instead.
func (*NodeIdentity) Descriptor() ([]byte, []int) {
	return file_hydra_common_proto_rawDescGZIP(), []int{0}
}

func (x *NodeIdentity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeIdentity) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeIdentity) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *NodeIdentity) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *NodeIdentity) GetDeploy() DeployTarget {
	if x != nil {
		return x.Deploy
	}
	return DeployTarget_DEPLOY_TARGET_UNSPECIFIED
}

type HealthReport struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Identity *NodeIdentity          `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	State    HealthState            `protobuf:"varint,2,opt,name=state,proto3,enum=hydra.common.v1.HealthState" json:"state,omitempty"`
	Detail   string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"` // free text, same convention as the
	// dashboard's own "status-detail" field
	Metrics       map[string]string `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // open key/value pairs - each family
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_hydra_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_hydra_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_hydra_common_proto_rawDescGZIP(), []int{1}
}

func (x *HealthReport) GetIdentity() *NodeIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *HealthReport) GetState() HealthState {
	if x != nil {
		return x.State
	}
	return HealthState_HEALTH_STATE_UNSPECIFIED
}

func (x *HealthReport) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *HealthReport) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_hydra_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_hydra_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_hydra_common_proto_rawDescGZIP(), []int{2}
}

var File_hydra_common_proto protoreflect.FileDescriptor

const file_hydra_common_proto_rawDesc = "" +
	"\n" +
	"\x12hydra_common.proto\x12\x0fhydra.common.v1\"\x9f\x01\n" +
	"\fNodeIdentity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x16\n" +
	"\x06family\x18\x04 \x01(\tR\x06family\x125\n" +
	"\x06deploy\x18\x05 \x01(\x0e2\x1d.hydra.common.v1.DeployTargetR\x06deploy\"\x97\x02\n" +
	"\fHealthReport\x129\n" +
	"\bidentity\x18\x01 \x01(\v2\x1d.hydra.common.v1.NodeIdentityR\bidentity\x122\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1c.hydra.common.v1.HealthStateR\x05state\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12D\n" +
	"\ametrics\x18\x04 \x03(\v2*.hydra.common.v1.HealthReport.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\a\n" +
	"\x05Empty*\x95\x01\n" +
	"\fDeployTarget\x12\x1d\n" +
	"\x19DEPLOY_TARGET_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DEPLOY_TARGET_CM5\x10\x01\x12\x19\n" +
	"\x15DEPLOY_TARGET_USER_PC\x10\x02\x12\x18\n" +
	"\x14DEPLOY_TARGET_MOBILE\x10\x03\x12\x1a\n" +
	"\x16DEPLOY_TARGET_WEARABLE\x10\x04*w\n" +
	"\vHealthState\x12\x1c\n" +
	"\x18HEALTH_STATE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fHEALTH_STATE_OK\x10\x01\x12\x19\n" +
	"\x15HEALTH_STATE_DEGRADED\x10\x02\x12\x1a\n" +
	"\x16HEALTH_STATE_UNHEALTHY\x10\x032O\n" +
	"\rHealthService\x12>\n" +
	"\x05Check\x12\x16.hydra.common.v1.Empty\x1a\x1d.hydra.common.v1.HealthReportBEZCgithub.com/JuanenRac/hydra-common-proto/hydracommonpb;hydracommonpbb\x06proto3"

var (
	file_hydra_common_proto_rawDescOnce sync.Once
	file_hydra_common_proto_rawDescData []byte
)

func file_hydra_common_proto_rawDescGZIP() []byte {
	file_hydra_common_proto_rawDescOnce.Do(func() {
		file_hydra_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hydra_common_proto_rawDesc), len(file_hydra_common_proto_rawDesc)))
	})
	return file_hydra_common_proto_rawDescData
}

var file_hydra_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hydra_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hydra_common_proto_goTypes = []any{
	(DeployTarget)(0),    // 0: hydra.common.v1.DeployTarget
	(HealthState)(0),     // 1: hydra.common.v1.HealthState
	(*NodeIdentity)(nil), // 2: hydra.common.v1.NodeIdentity
	(*HealthReport)(nil), // 3: hydra.common.v1.HealthReport
	(*Empty)(nil),        // 4: hydra.common.v1.Empty
	nil,                  // 5: hydra.common.v1.HealthReport.MetricsEntry
}
var file_hydra_common_proto_depIdxs = []int32{
	0, // 0: hydra.common.v1.NodeIdentity.deploy:type_name -> hydra.common.v1.DeployTarget
	2, // 1: hydra.common.v1.HealthReport.identity:type_name -> hydra.common.v1.NodeIdentity
	1, // 2: hydra.common.v1.HealthReport.state:type_name -> hydra.common.v1.HealthState
	5, // 3: hydra.common.v1.HealthReport.metrics:type_name -> hydra.common.v1.HealthReport.MetricsEntry
	4, // 4: hydra.common.v1.HealthService.Check:input_type -> hydra.common.v1.Empty
	3, // 5: hydra.common.v1.HealthService.Check:output_type -> hydra.common.v1.HealthReport
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_hydra_common_proto_init() }
func file_hydra_common_proto_init() {
	if File_hydra_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hydra_common_proto_rawDesc), len(file_hydra_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hydra_common_proto_goTypes,
		DependencyIndexes: file_hydra_common_proto_depIdxs,
		EnumInfos:         file_hydra_common_proto_enumTypes,
		MessageInfos:      file_hydra_common_proto_msgTypes,
	}.Build()
	File_hydra_common_proto = out.File
	file_hydra_common_proto_goTypes = nil
	file_hydra_common_proto_depIdxs = nil
}
