// =============================================================================
// HYDRA-UMC Ecosystem - proto/hydra_common.proto
// Copyright (C) 2026 JuanenRac (Electro Hobby 3D) <electrohobby3d@gmail.com>
// GPL-3.0 - see LICENSE
//
// Shared gRPC contract for node-to-node traffic across the ecosystem's AI
// and orchestration nodes (Vision AI Node, Cognitive AI Node, Orchestration
// & Swarm, Digital Twin & Simulation families).
//
// This does NOT replace:
//   - REST + WebSocket between STUDIO/HYDRA-UMC-ANDROID-CONTROL/
//     HYDRA-UMC-IOS-CONTROL and HYDRA-UMC-SERVER (human-facing client
//     traffic, out of scope here).
//   - CAN / CAN-OTA on the real HYDRA-UMC/URTC firmware (STM32 boards do
//     not, and will not, speak gRPC).
//   - The physical E-STOP signal path: HYDRA-UMC-SAFETY-ZONES may request
//     a stop over this channel, but the firmware is what actually asserts
//     it over CAN, independent of this protocol's own health.
//
// Design rationale, alternatives considered, and per-family service sketch:
// see SONNET/13.DISENO_GRPC_NODOS_IA.txt (private planning doc, not part of
// this public repo).
//
// Status: v0. HealthService (below) is meant to be implemented by every
// node without exception - it is what lets HYDRA-UMC-NODE-HEALING probe
// any node in the ecosystem the same way. Per-family business services
// (vision detections, cognitive intents, job dispatch, physics stepping,
// ...) are intentionally NOT defined here yet - they get their own .proto
// file once each node's real logic lands, once there's an actual
// implementation to design the exact message shape against.
// =============================================================================

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: hydra_common.proto

package hydracommonpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthService_Check_FullMethodName = "/hydra.common.v1.HealthService/Check"
)

// HealthServiceClient is the client API for HealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The one service every node is expected to implement, no exceptions.
// HYDRA-UMC-NODE-HEALING is the primary client, but any node may probe
// any other node (e.g. HYDRA-UMC-ORCHESTRATOR checking on
// HYDRA-UMC-JOB-DISPATCHER before assigning it work).
type HealthServiceClient interface {
	Check(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReport, error)
}

type healthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthServiceClient(cc grpc.ClientConnInterface) HealthServiceClient {
	return &healthServiceClient{cc}
}

func (c *healthServiceClient) Check(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReport)
	err := c.cc.Invoke(ctx, HealthService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServiceServer is the server API for HealthService service.
// All implementations must embed UnimplementedHealthServiceServer
// for forward compatibility.
//
// The one service every node is expected to implement, no exceptions.
// HYDRA-UMC-NODE-HEALING is the primary client, but any node may probe
// any other node (e.g. HYDRA-UMC-ORCHESTRATOR checking on
// HYDRA-UMC-JOB-DISPATCHER before assigning it work).
type HealthServiceServer interface {
	Check(context.Context, *Empty) (*HealthReport, error)
	mustEmbedUnimplementedHealthServiceServer()
}

// UnimplementedHealthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServiceServer struct{}

func (UnimplementedHealthServiceServer) Check(context.Context, *Empty) (*HealthReport, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedHealthServiceServer) mustEmbedUnimplementedHealthServiceServer() {}
func (UnimplementedHealthServiceServer) testEmbeddedByValue()                       {}

// UnsafeHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServiceServer will
// result in compilation errors.
type UnsafeHealthServiceServer interface {
	mustEmbedUnimplementedHealthServiceServer()
}

func RegisterHealthServiceServer(s grpc.ServiceRegistrar, srv HealthServiceServer) {
	// If the following call panics, it indicates UnimplementedHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthService_ServiceDesc, srv)
}

func _HealthService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).Check(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthService_ServiceDesc is the grpc.ServiceDesc for HealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hydra.common.v1.HealthService",
	HandlerType: (*HealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _HealthService_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hydra_common.proto",
}
